name: CI

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-note@v1
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: npm install

      - name: build React App
        run: npm run build
